apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dagster-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce  # both containers are in the same pod so RWO is fine
  storageClassName: {{ .Values.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
