---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: minio-credentials
  namespace: local-datalake
spec:
  encryptedData:
    root-password: AgBv83++fz/AsnhoXOu8QxR5r1t1iEj21t1/qN6r5+/8trRufawdlpclLAVJkRXkwV2CXoC5UTRrqc/omo4emD41hyW2Y/nAk+3aDo7aACBrqpIsNc+MTemlrkuejP5hTplIHB35O8NpOr0MmFjI4aKS41Tr+CQHBYP50ljOqDvmdtLNKhOd6pBw8gp3n4vQf2W7zMXxazm9JP6GZPHQcDsluU01sbrB2UVVJHLTEGQrrczCEdt0ssh8fGUZGovlEcqzpOp7LGs5Hkyai31e24Z0Tspcn/NHzgYnxDG3rxt8DPtdBKKTG6xkQZ34lnFELjCzzMC015bznUFXX4hr87iCR3w/gle5N4LtoAg9q+jc2rA090bzu5sLm0omfwTJ9QtaEKOaA0pTFIPudTLCGNGenbOjxOseZ5MCpliWnUJV8EuOGgQ6cYfEobpvHVj+OTbwwBoziSqW5+HZWWHSqXN+h6coxtxWuH1LJPkGLyN/R/xNFQfTpT9aVAEBEmjkR3seXhjBhj1L3A2JCDEAKKf1NJqbJCXnfFlGkcVyqAeJCPX5yCsM535fT/nLaI7J7XfNcKfjc7Z7pCmB1A/HPP+fjzdj4ERzuEekPoIcYPr897sQA8EBUFvW/L65Asr80DjpYRQUGvSBHYAmD7SFpKpQzCBEc8ymkp4utgDZWTIItI8Uk9IIdJ9e24ykmvX1bOItSv0zt1LrDLJd+/p6
    root-user: AgDCGQgdiGdddKp4ebSChd0lV2GEFlYm0hI25OElpPBMiLzTIotcYN8E6Qto/vAUjYxRUwQOBZ3YJHgEoe0l3s1VNs03/zW0R+1FEegjFLqjoZlRiAXXdbDEWLkPSMWZa6KisfD+NqSo2FA11VRzN/6LbGQkBrf8OYiwNe/Fww7BDuSyUi6jXvEL+x/USUPs7Fln7X8Rkgub3lGPdEeo6G0wVUNd3joVD0RUwaYBzsEkxrfKXYob9EruZozq8i+SRCFqNe0f870ZJ9QQHT84KEQ3hoult55HXqo6KLxXleXRnaC1cnfdJptlbpit48rtlQoYDS16Lo2qQ6m/PnYrhAxefGuB7x3tE4hHRcZhXABp8wjWh2FmEi1NieQ2LiH8VH8tWcn1ZAxgZds/bm51sH9QStZArSWUg/1HRdHfoeEbEsq5UGN1yu0Z5XoTmfpUMIl/JVR7YXpBmj/FntF45RqWGT2229S7JyGl6EDX39j0MrDAtClInBj2IhqDEYHV4yVjKG1LtYra/rkhg22rJniihnOoFG6BMvE8TvIEb6dJHsMzBPeXBy8VQKv8MRhzikFP3ruR4Ojg8GFqu5AvhEkypb7C4Glw44WGIZnA5h4RPiukhCd+kcYiTfxuHkR8gyMIt2IzB8OnZMAJxsfTI/ZJCut6f9Tde4h8bAaokE4vEVxXlutTupsIBiMq6mPCUbB49WUca0+YswSY
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: minio-credentials
      namespace: local-datalake
